---
title: "Lab 2"
author: "Daniel Addo"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
```

# Design 1
```{r}
design_one <- function(N_samp = 228, # Total number of participants
                       trt_n = 4, # Number of Arms
                       trt_effect = rep(0.35,4), # treatment effect for each arm 
                       alpha = 0.35,  beta = 0.65, # prior
                       n_post = 1000, # number of posterior draws
                       seed_setting = 8, # set seed for replication
                       allocation_size = 40 # Initial Sample to allocate
                       ){
  set.seed(seed_setting)
  n_samp <- N_samp/trt_n
  Y <- NULL
  post_y <- NULL
  for(i in 1:trt_n){
    # Definition of outcome given treatment effect within each arm
    Y[[i]] <- rbinom(n_samp,1,trt_effect[i])
    # Posterior draws
    post_y[[i]] <- rbeta(n_post, 
                         alpha + sum(Y[[i]]), 
                         beta + n_samp - sum(Y[[i]])
                         )
  }
  # Compare treatments with control and select best
  comparison_means <- sapply(2:(trt_n), function(x) mean(post_y[[x]]>post_y[[1]]))
  max_trt<-which.max(comparison_means)
  max_trt_prob <- comparison_means[max_trt]
  output <- NULL
  output[[1]] <- noquote(paste("The best treatment arm with probability of",
                      "being better than control is treatment",
                       max_trt, "with probability",
                       round(max_trt_prob,2)
                       ))
  output[[2]] <- cbind(Treatment = 0:(trt_n-1),
                       Size = rep(n_samp,trt_n))
  return(output)
}

design_one(N_samp, trt_n, trt_effect,
           alpha, beta, n_post, seed_setting)


```

# Design 2 (incomplete)
```{r}
set.seed(8)
design_two <- function(N_samp = 228, # Total number of participants
                       trt_n = 4, # Number of Arms
                       trt_effect = rep(0.35,4), # treatment effect for each arm 
                       alpha = 0.35,  beta = 0.65, # prior
                       n_post = 1000, # number of posterior draws
                       seed_setting = 8, # set seed for replication
                       allocation_size = 40 # Initial Sample to allocate
                       ){
  set.seed(seed_setting) # Set seed
  interim_steps <- ceiling(N_samp/allocation_size) # Compute # of steps needed
  n_samp <- NULL
  for(j in 1:interim_steps){
    Y <- NULL
    post_y <- NULL
    post_y_all <- NULL
    # Define allocation probabilities
    if(j==1){ # First time, allocate equally across treatments
      allocation_prob <- rep(1,trt_n)/trt_n
    }else{ # Allocate according to allocation probs across treatments
      allocation_prob <- V_t_norm
    }
  for(i in 1:trt_n){
    # Sample size update
    if(j==1){ # First time, use initial arguments
      n_samp[i] <-(allocation_prob[i]*allocation_size) |> round()
    }else if(j!=interim_steps){ # Update samples sizes prior to last step
      n_samp[i] <-((allocation_prob[i]*allocation_size)+n_samp[i]) |> round()
    }else{ # Allocate remaining sample size
      n_samp[i] <-((allocation_prob[i]*(N_samp %% allocation_size))+n_samp[i]) |> round()
    } 
    # Definition of outcome given treatment effect within each arm
     Y[[i]] <- rbinom(n_samp[i],1,trt_effect[i])
    # Posterior draws
    post_y[[i]] <- rbeta(n_post, 
                         alpha + sum(Y[[i]]), 
                         beta + n_samp[i] - sum(Y[[i]])
                         )
    post_y_all <- cbind(post_y_all,post_y[[i]])
  }
  pt_max0 <- apply(post_y_all, 1, which.max) |> table() |> as.data.frame()
  names(pt_max0) <- c("Treatment", "Frequency")
  pt_max <- data.frame(Treatment=c(1:trt_n)) |>
    merge(pt_max0, all.x=TRUE) |>
    transform(Frequency= ifelse(is.na(Frequency),0,Frequency)) |>
    transform(Propor = Frequency/n_post
              )
  
  # Update allocation probability
  aaa <- sum(pt_max[-1,3] * (n_samp[-1]+1)/(n_samp[1]+1)) 
  bbb <- max(pt_max[-1,3])
  V_0 <- min(aaa,bbb)
  V_t <- c(V_0, pt_max[-1,3])
  V_t_norm <- V_t/sum(V_t) # Normalize to get allocation probabilities
  }
  
  
  # Compare treatments with control and select best
  comparison_means <- sapply(2:(trt_n), function(x) mean(post_y[[x]]>post_y[[1]]))
  max_trt<-which.max(comparison_means)
  max_trt_prob <- comparison_means[max_trt]
  output <- NULL
  output[[1]] <- noquote(paste("The best treatment arm with probability of",
                      "being better than control is treatment",
                       max_trt, "with probability",
                       round(max_trt_prob,2)
                       ))
  output[[2]] <- cbind(Treatment = 0:(trt_n-1),
                       Size = n_samp)
  return(output)
}

design_two(N_samp = 228, # Total number of participants
           trt_n = 4, # Number of Arms
           trt_effect = rep(0.35,4), # treatment effect for each arm 
           alpha = 0.35,  beta = 0.65, # prior
           n_post = 1000, # number of posterior draws
           seed_setting = 9, # set seed for replication
           allocation_size = 40 # Initial Sample to allocate
           )
```
